- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php' update_cache=yes


- name: Update
  become: yes
  command: apt update

- name: Install php-fpm & php extensions
  become: true
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - php-pear
    - php7.3-curl
    - php7.3-dev
    - php7.3-gd
    - php7.3-mbstring
    - php7.3-zip
    - php7.3-mysql
    - php7.3-xml
    - php7.3-fpm
    - php7.3-imagick
    - php7.3-recode
    - php7.3-tidy
    - php7.3-xmlrpc
    - php7.3-intl

- name: Configure php-fom with apache2
  become: true
  copy: src=files/www.conf dest=/etc/php/7.3/fpm/pool.d/

- name: Configure php.ini
  become: true
  copy: src=files/php.ini dest=/etc/php/7.3/fpm/

- name: Restart php-fpm
  become: yes
  service: name=php7.3-fpm state=restarted
